# 1.Multiply the two matrices.


In [35]:
A = [[1, 4, 3], 
    [3, 5, 6], 
    [6, 7, 9]] 
 
B = [[1, 2, 5, 12], 
    [6, 7, 3, 0], 
    [4, 7, 9, 11]]  
result = [[sum(a * b for a, b in zip(A_row, B_col))  
                        for B_col in zip(*B)] 
                                for A_row in A] 
  
for r in result: 
    print(r) 

[37, 51, 44, 45]
[57, 83, 84, 102]
[84, 124, 132, 171]


# Extract all numbers divisible by 3 from the array
Input:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9,10,11,12])
Desired output:
#> array([3,6,9,12])


In [72]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9,10,11,12])

In [73]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [77]:
arr[arr %3==0]

array([ 0,  3,  6,  9, 12])

# How to get the unique common items between two python numpy arrays?
Q. Get the unique common items between a and b
Input:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
Desired Output:
array([2, 4])


In [75]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

# How to remove from one array those items that exist in another?
Q. From array a remove all items present in array b
Input:
a = np.array([1,2,3,4,5,11,22,33,44,55])
b = np.array([5,6,7,8,9,10,11])
Desired Output:
array([1,2,3,4,22,33,44,55])


In [78]:

a = np.array([1,2,3,4,5,11,22,33,44,55]) 
b = np.array([5,6,7,8,9,10,11]) 
np.setdiff1d(a,b)

array([ 1,  2,  3,  4, 22, 33, 44, 55])

# How to get the positions where elements of two arrays match?
Q. Get the positions where elements of a and b match
Input:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
Desired Output:
#> (array([1, 3, 5, 7]))


In [81]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

# How to create a 2D array containing random floats between 10 and 25?
Q. Create a 2D array of shape 5x3 to contain random decimal numbers between 10 and 25.


In [82]:
a=np.random.uniform(low=10, high=25,size=(5,3))
a


array([[10.0228087 , 20.84936232, 23.6282021 ],
       [15.16531618, 19.66751318, 21.50738202],
       [18.57505587, 10.04515354, 14.21525808],
       [11.95804452, 20.53571036, 17.82078231],
       [23.89436485, 10.85305402, 10.28099743]])

# Take a string as input. Create a new string that is the reverse of the first string.
    A =”Hello”
    Result = “olleH”


In [93]:
a="Hello"
print(a)
a[::-1]

Hello


'olleH'

# Write a Python program to remove the first occurrence of a specified element  (ex 7 ) from an array.
   Repeat the same for all occurrences of 7


In [3]:
from array import *
array_num = array('i', [1, 3, 7, 3, 7, 1, 9,7, 3])
print(str(array_num))
print("Remove the first occurrence of 7 from the said array:")
array_num.remove(7)
print("New array: "+str(array_num))

array('i', [1, 3, 7, 3, 7, 1, 9, 7, 3])
Remove the first occurrence of 7 from the said array:
New array: array('i', [1, 3, 3, 7, 1, 9, 7, 3])


# Write a Python program that iterate over elements repeating each as many times as its count.

# Write a Python program to find the occurrences of 10 most common words in a given text.
Do the same for words which are at least 4 characters long.


# Create a python program to generate the Fibonocci series.

In [1]:
n = input('Enter the number of terms')
def fibo(n):
    if n <= 1:
        return n
    else:
        return(fibo(n-1) + fibo(n-2))

for i in range(int(n)):
    print(fibo(i), end=' ')

Enter the number of terms15
0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 