# Write a python program to take a 3X3 matrix as a user input. Convert the matrix into numpy array. Print the matrix, rank, shape of the matrix.

In [1]:
import numpy as np
mat=[[int(input()) for x in range (3)] for y in range(3)] 

1
2
3
4
5
6
7
8
9


In [2]:
m=np.matrix(mat)
print(m)
shape=m.shape #shape of matrix
print(shape) 
np.linalg.matrix_rank(m) #rank of matrix


[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


2

In [34]:
type(m)

numpy.matrix

In [60]:
b=np.array(m).flatten() #converting matrix to array  
print(b)
type(b)

[1 2 3 4 5 6 7 8 9]


numpy.ndarray

# Write a function that generates 10 integers and use it to build an array

In [5]:
import numpy as np
a=np.random.randint(5, size=(10))
print (a)

[2 2 1 2 3 4 0 0 4 4]


In [6]:

np.array(a)

array([2, 2, 1, 2, 3, 4, 0, 0, 4, 4])

# Create a random vector (1D array) of size 10 and sort it

In [19]:
import numpy as np
a=np.random.randint(5, size=(10))

In [20]:
a

array([4, 1, 3, 4, 2, 4, 0, 2, 4, 0])

In [22]:
a.sort()
a

array([0, 0, 1, 2, 2, 3, 4, 4, 4, 4])

# Write a Python program to generate five random numbers from the normal distribution. [Hint: use np.random.normal]

In [29]:
import numpy as np
a=np.random.normal(5, size=(5))
a

array([6.29926378, 4.68998399, 5.84280749, 6.18927975, 4.4490223 ])

# Write a numpy program program to add and subtract two random matrices. The size of the matrix will a user input. All the matrix element should be a positive integer value. Suppose 'A' and 'B' are two matrix. All the value of 'A' matrix cannot be greater than 10 and values of 'B' matrix cannot be greater than 20.

In [7]:
import numpy as np

x=int(input())
y=int(input())
a=np.random.randint(10, size=(x*y))
b=np.random.randint(20, size=(x*y))
c=np.reshape(a,(x,y))
m1=np.matrix(c)
print("matrix 1\n",m1)
d=np.reshape(b,(x,y))
m2=np.matrix(d)
print("matrix 2\n",m2)

2
2
matrix 1
 [[8 1]
 [4 1]]
matrix 2
 [[ 9 15]
 [19  8]]


In [8]:
add=m1+m2
print ("matrix1 + matrix2\n",add)
sub=m1-m2
print("matrix1 - matrix2\n",sub)

matrix1 + matrix2
 [[17 16]
 [23  9]]
matrix1 - matrix2
 [[ -1 -14]
 [-15  -7]]


# 6. Write a numpy program program to multiply two random matrices. The size of the matrices will a user input. All the matrix element should be a positive integer value. Suppose 'A' and 'B' are two matrix. All the value of 'A', 'B' matrices cannot be greater than 10.

In [9]:
import numpy as np

x=int(input())
y=int(input())
a=np.random.randint(10, size=(x*y))
c=np.reshape(a,(x,y))
m1=np.matrix(c)
print("matrix 1\n",m1)
i=int(input())
o=int(input())
b=np.random.randint(10, size=(i*o))
d=np.reshape(b,(i,o))
m2=np.matrix(d)
print("matrix 2\n",m2)

1
2
matrix 1
 [[7 6]]
2
3
matrix 2
 [[3 6 1]
 [9 4 9]]


In [10]:
m1*m2

matrix([[75, 66, 61]])

# 7. Write a python program 4.py to take nXm matrix as a user input. 'n' and 'm' are command line argument which are separated by a space. Where n >= 3 and 0>=m<=7. If this condition is false, ask the user to enter the 'n' and 'm' again. Create a zero matrix with same dimension and convert all columns in the matrix into a fibonacci series. For ith column, the first element should be the sum of i+(i-1) value. Print this matrix on the terminal.

In [ ]:
# Program to display the Fibonacci sequence up to n-th term
import numpy as np
a = int(input())
b = int(input())
c=7
# first two terms
n1, n2 = 0, 1
count = 0
if (a)<3 :
    print("invalid number , please enter another number")
if b<0 and b>8:
    #print("invalid number , please enter another number")
elif (a*b) <= 0:
    print("invalid number , please enter another number ")
elif (a*b) == 1:
    print("Fibonacci sequence upto",(a*b),":")
    print(n1)
else:
    print("Fibonacci sequence:")
    while count < (a*b):
        print(n1)
        nth = n1 + n2
       # update values
        n1 = n2
        n2 = nth
        count += 1

In [56]:
print("Fibonacci sequence upto",(a*b),":")

Fibonacci sequence upto 9 :


AttributeError: 'builtin_function_or_method' object has no attribute 'matrix'

In [6]:
import numpy as np
n = int(input('Enter the number of terms'))
m = int(input('enter'))
c=(n*m)
def fibo(c):
    if n <= 1:
        return c
    else:
        return(fibo(c-1) + fibo(c-2))

for i in range(int(c)):
    print(fibo(i), end=' ')

Enter the number of terms2
enter3


RecursionError: maximum recursion depth exceeded in comparison