# How to replace items that satisfy a condition with another value in numpy array?

In [4]:
import numpy as np
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr)
arr[arr % 2 == 1] = -1
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[ 0 -1  2 -1  4 -1  6 -1  8 -1]


# How to reshape an array? (2 Points)
Convert a ID array to a 2D array with 2 rows

In [15]:
import numpy as np
m=np.arange(10)
print("1D array =",m)
print("2D array =",m.reshape(2,-1))

1D array = [0 1 2 3 4 5 6 7 8 9]
2D array = [[0 1 2 3 4]
 [5 6 7 8 9]]


# How to generate custom sequences in numpy without hardcoding?
Create the following pattern without hardcoding. Use only numpy functions and the below input array , 
arr =np.array([1,2,3]) ,
Desired Output:array ([1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [33]:
import numpy as np
a = np.array([1,2,3])
print("array =",a)
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array = [1 2 3]


array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

# How to get the common items between two python numpy arrays?

In [37]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print("a=",a)
print("b=",b)
np.intersect1d(a,b)

a= [1 2 3 2 3 4 3 4 5 6]
b= [ 7  2 10  2  7  4  9  4  9  8]


array([2, 4])

# How to get the positions where elements of two arrays match?
Get the positions where elements of a and b match

In [38]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print("a=",a)
print("b=",b)

a= [1 2 3 2 3 4 3 4 5 6]
b= [ 7  2 10  2  7  4  9  4  9  8]


In [41]:
c=np.where(a==b)
print("positions where elements of two arrays match=",c)

positions where elements of two arrays match= (array([1, 3, 5, 7], dtype=int64),)


# How to create a 2D array containing random floats between 5 and 10?
Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.

In [63]:
a=np.random.uniform(low=5, high=10,size=(5,3))
a



array([[8.6501701 , 7.70852823, 5.0511063 ],
       [5.40396784, 7.40815767, 6.25679832],
       [9.88760078, 9.0795365 , 7.65998874],
       [5.10947507, 5.24067448, 9.57161518],
       [6.29673184, 9.20190764, 9.61773827]])

# How to limit the number of items printed in output of numpy array to 6?
Limit the number of items printed in python numpy array a to a maximum of 6 elements.
arr = np.arange(15)
Desired Output:array([ 0, 1, 2, ..., 12, 13, 14])

In [87]:
arr = np.arange(15)
np.set_printoptions(threshold=6)
arr

array([ 0,  1,  2, ..., 12, 13, 14])

# How to pretty print a numpy array by suppressing the scientific notation (like 1el0)?
Limit the number of items printed in python numpy array a to a maximum of 6 elements.
np.random.seed(100)
rand_arr=np.random.random([3,3])/1e3
Desired Output:array([[ 0.000543, 0.000278, 0.000425], [ 0.000845, 0.000005, 0.000122], [ 0.000671 , 0.000826, 0.0001371]])

In [76]:
np.random.seed(100)
arr=np.random.random([3,3])/1e3
arr
np.set_printoptions(suppress=False)
np.set_printoptions(suppress=True, precision=6)
arr

array([[0.000543, 0.000278, 0.000425],
       [0.000845, 0.000005, 0.000122],
       [0.000671, 0.000826, 0.000137]])

# How to swap two columns in a 2d numpy array?
Swap columns 1 and 2 in the array arr.

In [84]:
import numpy as np
my_array = np.arange(9).reshape(3, 3)
print(" array\n")
print(my_array)
my_array[:,[0, 1]] = my_array[:,[1, 0]]
print("After swapping\n")
print(my_array)

 array

[[0 1 2]
 [3 4 5]
 [6 7 8]]
After swapping

[[1 0 2]
 [4 3 5]
 [7 6 8]]
